"""Audiobookshelf integration for shelfr."""

from __future__ import annotations

from shelfr.abs.asin import (
    AUDIO_EXTENSIONS,
    AsinEntry,
    AsinSource,
    SearchMatch,
    asin_exists,
    build_asin_index,
    build_asin_index_async,
    extract_all_asins,
    extract_asin,
    extract_asin_from_abs_item,
    extract_asin_with_source,
    is_valid_asin,
    match_search_results,
    resolve_asin_via_abs_search,
)
from shelfr.abs.async_client import AbsAsyncClient
from shelfr.abs.cleanup import (
    CLEANUP_ELIGIBLE_STATUSES,
    CleanupError,
    CleanupPrefs,
    CleanupResult,
    CleanupStatus,
    CleanupStrategy,
    cleanup_source,
    is_cleanup_eligible,
    should_ignore_folder,
    verify_seed_exists,
)
from shelfr.abs.client import (
    AbsApiError,
    AbsAuthError,
    AbsClient,
    AbsConnectionError,
    AbsLibrary,
    AbsLibraryItem,
    AbsUser,
)
from shelfr.abs.importer import (
    BatchImportResult,
    DuplicateError,
    FilesystemMismatchError,
    ImportError,
    ImportResult,
    ParsedFolderName,
    build_target_path,
    discover_staged_books,
    import_batch,
    import_batch_async,
    import_single,
    parse_mam_folder_name,
    trigger_scan_safe,
    validate_import_prerequisites,
)
from shelfr.abs.paths import PathMapper, abs_path_to_host, host_path_to_abs
from shelfr.abs.prefetch import (
    AsinMetadataCache,
    PrefetchResult,
    PrefetchSummary,
    extract_asins_from_folders,
    get_cached_metadata,
    has_cached_metadata,
    prefetch_metadata_async,
    prefetch_single_async,
)
from shelfr.abs.rename import (
    AbsMetadata,
    RenameCandidate,
    RenameResult,
    RenameStatus,
    RenameSummary,
    detect_duplicates,
    detect_edition_flags,
    discover_rename_candidates,
    generate_report,
    parse_abs_metadata,
    run_rename_pipeline,
)

__all__ = [
    # ASIN extraction and in-memory index
    "AUDIO_EXTENSIONS",
    # Cleanup
    "CLEANUP_ELIGIBLE_STATUSES",
    # Client
    "AbsApiError",
    "AbsAsyncClient",
    "AbsAuthError",
    "AbsClient",
    "AbsConnectionError",
    "AbsLibrary",
    "AbsLibraryItem",
    # Rename
    "AbsMetadata",
    "AbsUser",
    "AsinEntry",
    # Prefetch (Phase 11.3)
    "AsinMetadataCache",
    "AsinSource",
    # Importer
    "BatchImportResult",
    "CleanupError",
    "CleanupPrefs",
    "CleanupResult",
    "CleanupStatus",
    "CleanupStrategy",
    "DuplicateError",
    "FilesystemMismatchError",
    "ImportError",
    "ImportResult",
    "ParsedFolderName",
    # Paths
    "PathMapper",
    "PrefetchResult",
    "PrefetchSummary",
    "RenameCandidate",
    "RenameResult",
    "RenameStatus",
    "RenameSummary",
    "SearchMatch",
    "abs_path_to_host",
    "asin_exists",
    "build_asin_index",
    "build_asin_index_async",
    "build_target_path",
    "cleanup_source",
    "detect_duplicates",
    "detect_edition_flags",
    "discover_rename_candidates",
    "discover_staged_books",
    "extract_all_asins",
    "extract_asin",
    "extract_asin_from_abs_item",
    "extract_asin_with_source",
    "extract_asins_from_folders",
    "generate_report",
    "get_cached_metadata",
    "has_cached_metadata",
    "host_path_to_abs",
    "import_batch",
    "import_batch_async",
    "import_single",
    "is_cleanup_eligible",
    "is_valid_asin",
    "match_search_results",
    "parse_abs_metadata",
    "parse_mam_folder_name",
    "prefetch_metadata_async",
    "prefetch_single_async",
    "resolve_asin_via_abs_search",
    "run_rename_pipeline",
    "should_ignore_folder",
    "trigger_scan_safe",
    "validate_import_prerequisites",
    "verify_seed_exists",
]
