"""Utility modules for MAMFast."""

from shelfr.utils.editor import (
    EditorError,
    NoEditorError,
    edit_file,
    edit_json,
    edit_temp,
    edit_yaml,
    edit_yaml_temp,
    get_editor,
)
from shelfr.utils.mini_editor import (
    MiniEditorError,
    MiniEditorNotAvailable,
    check_available as is_tui_available,
    edit_file_inline,
    edit_json_inline,
    edit_yaml_inline,
    mini_edit,
)
from shelfr.utils.preview import (
    preview_bbcode,
    preview_diff,
    preview_file,
    preview_json,
    preview_markdown,
    preview_side_by_side,
    preview_validation_result,
    preview_yaml,
    preview_yaml_structure,
)
from shelfr.utils.fuzzy import (
    ChangeAnalysis,
    DuplicatePair,
    analyze_change,
    find_best_match,
    find_duplicates,
    find_duplicates_in_groups,
    find_matches,
    group_similar_series,
    is_suspicious_change,
    match_name,
    normalize_author_name,
    normalize_series_name,
    partial_ratio,
    similarity_ratio,
    weighted_ratio,
)
from shelfr.utils.paths import safe_dirname, safe_filename, safe_filepath

__all__ = [
    "safe_dirname",
    "safe_filename",
    "safe_filepath",
    # Editor utilities
    "EditorError",
    "NoEditorError",
    "edit_file",
    "edit_json",
    "edit_temp",
    "edit_yaml",
    "edit_yaml_temp",
    "get_editor",
    # Fuzzy matching utilities
    "ChangeAnalysis",
    "DuplicatePair",
    "analyze_change",
    "find_best_match",
    "find_duplicates",
    "find_duplicates_in_groups",
    "find_matches",
    "group_similar_series",
    "is_suspicious_change",
    "match_name",
    "normalize_author_name",
    "normalize_series_name",
    "partial_ratio",
    "similarity_ratio",
    "weighted_ratio",
    # Mini editor utilities (Tier 2)
    "MiniEditorError",
    "MiniEditorNotAvailable",
    "edit_file_inline",
    "edit_json_inline",
    "edit_yaml_inline",
    "is_tui_available",
    "mini_edit",
    # Preview utilities (Tier 2)
    "preview_bbcode",
    "preview_diff",
    "preview_file",
    "preview_json",
    "preview_markdown",
    "preview_side_by_side",
    "preview_validation_result",
    "preview_yaml",
    "preview_yaml_structure",
]
